app:
    resource: "@AppBundle/Controller/"
    type:     annotation
home:
    path: /
    defaults: {_controller: AppBundle:Index:index}
users:
	path: /users
	defaults: {_controller: AppBundle:UserManagement:users}
splash:
	path: /splash
	defaults: {_controller: AppBundle:Splash:splash}
event_show:
    path: /event/{id}
    defaults: {_controller: AppBundle:Event:show}
event_edit:
    path: /event/{id}/edit
    defaults: {_controller: AppBundle:Event:edit}
register:
    path:      /register
    defaults: {_controller: AppBundle:Register:register}