AppBundle\Entity\Party:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PartyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        registrantEmail:
            type: string
            length: 255
            column: registrant_email
        numSeats:
            type: integer
            column: num_seats
        wantsPairedWithBoater:
            type: boolean
            column: wants_paired_with_boater
        selectionStatus:
            type: string
            length: 255
            column: selection_status
        selectionStatusReason:
            type: string
            length: 255
            nullable: true
            column: selection_status_reason
        confirmedAttending:
            type: boolean
            column: confirmed_attending
        numActuallyAttended:
            type: integer
            nullable: true
            column: num_actually_attended
    lifecycleCallbacks: {  }
